### ISSUE TITLE
Push to statsd happens in UDP which is leading to metrics being missed to reach StatsD

### ISSUE THREAD

**Issue by alok87** [DataDog/php-datadogstatsd#133]
Is TCP an option to send data to StatsD? Can we push at some intervals only but push in TCP protocol?

**Comment by alok87** [comment]
We run a statsd daemonset

**Comment by gh123man** [comment]
Hi @alok87 - Only UPD and UDS (unix domain sockets) are support for dogstatsd.

**Comment by alok87** [comment]
@gh123man we see u allow push in TCP to data dog API. Can we use it somehow?

**Comment by alok87** [comment]
@gh123man our setup at present

php app (datadog client)----(UDP)-----> [StatsD exporter](https://github.com/prometheus/statsd_exporter) -> Prometheus

We are loosing events due to UDP, we want to convert that to TCP.

**Comment by alok87** [comment]
Changing this `socket_sendto` to `socket_write` can make it TCP i think - https://github.com/DataDog/php-datadogstatsd/blob/master/src/DogStatsd.php#L501 wdyt?

**Comment by gh123man** [comment]
> @gh123man we see u allow push in TCP to data dog API. Can we use it somehow?

The TCP feature in this library is specifically for sending events directly to the Datatadog API bypassing the agent/dogstatsd server. You can use this feature - but it behaves totally differently than the dogstatsd protocol. 

> Changing this socket_sendto to socket_write

While the statsd exporter supports TCP - dogstastd itself does not. So this is not going to be compatible out of the box without changes. Changing the socket method very well may work - but we likely won't take this as an upstream change since it's not actually compatible with the dogstatsd protocol.

**Comment by Ferror** [comment]
Ensuring the trustworthiness of metrics sent to Datadog should be the top priority. This will make the entire feature reliable and ultimately useful.

I'm missing something, or does DataDog have a better approach to sending metrics?

**Comment by gh123man** [comment]
@Ferror This library is designed to interface with the [Datadog agent](https://github.com/DataDog/datadog-agent) either via UDP or UDS. The agent sends aggregated metric payloads to the Datadog backend over HTTPS. 

The Agent itself does not support receiving dogstatsd metrics over TCP - so adding TCP socket support to this library would not work.
