### ISSUE TITLE
tags should be separated by comma only

### ISSUE THREAD

**Issue by phoet** [DataDog/php-datadogstatsd#35]
the implementation of tags in the client is inconsistent (and probably broken)

the [official dogstatsd](http://docs.datadoghq.com/guides/dogstatsd/#datagram-format) states this:

```
metric.name:value|type|@sample_rate|#tag1:value,tag2
```

so tags are attached via `#` and separated via `,`

this implementation can be found [in the ruby client](https://github.com/DataDog/dogstatsd-ruby/blob/master/spec/statsd_spec.rb#L331) for example.

it looks like this is also implemented correctly for [service-checks](https://github.com/DataDog/php-datadogstatsd/blob/master/libraries/datadogstatsd.php#L181-L184).

but it looks like it's wrong in the metrics implementation as it will [separate by `,#`](https://github.com/DataDog/php-datadogstatsd/blob/master/libraries/datadogstatsd.php#L147-L156)!

/cc @bonko @fungusakafungus

**Comment by hkaj** [comment]
Hi @phoet 

Thanks for reporting this. We'll investigate this and come back to you as soon as possible.

**Comment by miketheman** [comment]
I can confirm this problem. It appears to be [here](https://github.com/DataDog/php-datadogstatsd/blob/94503b8c40cab99c8b944ed5ed66b95fe35dd6c1/libraries/datadogstatsd.php#L168-L170) - where the logic is prepending the `|#` inside the for loop, instead of once at the beginning.
This could be restructured to do the same action for both array-based and string-based tags, and then perform the "joining" after.

**Comment by miketheman** [comment]
@hkaj any update here? Looks like a PR was submitted last month to address this.

**Comment by HasMatthew** [comment]
@hkaj Please take a look at open PR https://github.com/DataDog/php-datadogstatsd/pull/44, which I believe is a proposed fix for this issue. Tagging seems to be completely broken at the moment in this library.
