### ISSUE TITLE
Datadog increment/decrement not working

### ISSUE THREAD

**Issue by kevinralali** [DataDog/php-datadogstatsd#46]
is this function still working? Because I trying to use increment from example or by my self is not working. But the event function is working nicely.

I try to use increment, but nothing happen to my metric

**Comment by kevinralali** [comment]
sorry, my bad. It's because I am forgot to initialize the agent for UDP

**Comment by bittner** [comment]
@kevinralali Can you provide a sample code? Would be interesting if this helps us.

Because, I think, we have the same or a similar issue for PHP 5.6.30 on Debian Jessie. We can create an event, but not increment a value. (Datadog is investigating internally for this now, according to a support ticket we have opened.)

**Comment by kevinjon27** [comment]
@bittner 

`function sendDataEmail() {
    Datadogstatsd::configure(DOG_KEY, DOG_APP);

    $conn = new mysqli(SERVER, USER_DB, PASS_DB, SERVER_DB, PORT_DB);

    if ($conn->connect_error) {
        die("Connection failed: " . $conn->connect_error);
    }

    $sql = "SELECT count(*) as total
              FROM rl_bulk_mail 
              WHERE `status`=1 AND proses_time > DATE_SUB(NOW(), INTERVAL 5 MINUTE)";

    $query = $conn->query($sql);
    $total = 0;
    if ($query->num_rows > 0) {
        while($item = $query->fetch_object()){
            for ($i=0;$i < $item->total;$i++) {
                echo "sendDataEmail".PHP_EOL;
                Datadogstatsd::increment(DOG_ENDPOINT.'.bulk_email');
                $total++;
            }
        }

    }
}`

Do you have done to initialize the UDP agent?

**Comment by bittner** [comment]
The two Datadogstatsd calls (configure, increment) above are obvious.

But what do I have to do to "initialize the UDP agent"? I don't understand.

More Insights / Analysis Results
------------
I can see from the source code why we can create an event using this client, but not a metric:

- [event](https://github.com/DataDog/php-datadogstatsd/blob/master/libraries/datadogstatsd.php#L256-L336) uses `curl`, hence is an **API wrapper**.
- [increment](https://github.com/DataDog/php-datadogstatsd/blob/master/libraries/datadogstatsd.php#L107-L177) and [service_check](https://github.com/DataDog/php-datadogstatsd/blob/master/libraries/datadogstatsd.php#L190-L231), on the other hand, communicate **via sockets**.

IIUC, the latter code must run on the target host, otherwise there is not datadog-agent running to accept the socket connection. The API wrapper code, on the other hand, is independent from the datadog-agent and can run on our developer machines.

**Comment by kevinralali** [comment]
@bittner you should doing this https://app.datadoghq.com/account/settings#agent

**Comment by bittner** [comment]
@kevinralali Your link just brings me to the Datadog agent Installation Instructions page. UDP is not explicitly mentioned.

Do you intend that one needs to set up the agent properly (i.e. regularly, as with the "easy one-step install"? Then the statsd client calls should work?

We have that setup, our code for now looks as follows and works with [event](https://github.com/DataDog/php-datadogstatsd/blob/master/libraries/datadogstatsd.php#L256) but does nothing, even when deployed on the target host, when it's [increment](https://github.com/DataDog/php-datadogstatsd/blob/master/libraries/datadogstatsd.php#L107) or [service_check](https://github.com/DataDog/php-datadogstatsd/blob/master/libraries/datadogstatsd.php#L190):

```php
public function listAction()
{
    \Datadogstatsd::configure('ad**********cv', '0a************b3');
    \Datadogstatsd::service_check('something.service.check',
                                  \Datadogstatsd::OK,
                                  ['something:cron'],
                                  'dev.something.docker',
                                  'test');

    if (....
```
